name: native_file_explorer_launcher
description: A flutter plugin to launch the native file explorer/a file or get a list of supported applications for a desired file (Open with feature).
version: 1.2.0
homepage: https://github.com/skalio/native-file-explorer-launcher

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.2"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: NativeFileExplorerLauncherPlugin
      windows:
        pluginClass: NativeFileExplorerLauncherPlugin
